from __future__ import print_function
import os, site

#myPackagePath = os.path.join( os.path.dirname(os.path.abspath(__file__)), "packages")
myPackagePath = os.path.dirname(os.path.abspath(__file__))

pathspec = r"""
# Generated by QuantumComputer's installer (install_locally.py)
# In the lines below, list the paths where Python should look for
# supplied modules, one directory per line.
#
# If a directory does not exist when Python is started, it will be ignored.
%s
""" % myPackagePath

print("Adding path:", myPackagePath)

usp = site.getusersitepackages()
if not os.path.exists(usp):
    os.makedirs(usp)
    uspfile = os.path.join(usp, 'QC.pth')
    open(uspfile, 'w').write(pathspec)
    print('Wrote to ' + uspfile)
    print("QuantumComputer package installed successfully!")
